cmake_minimum_required(VERSION 3.31)
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/.devcontainer/cmake)
include(preproject)
project(buildpro)
set(externpro_REV 24.05)
find_package(externpro REQUIRED)
include(flags)
include(deps)
xpFindPkg(PKGS hdf5 libspatialite nasm nvjpeg2000 patch spatialite-tools)
xpSourceListAppend()
