set(pro nodexp)
set(tgt ${pro}_test)
add_library(${tgt} SHARED ${pro}.cpp)
target_link_libraries(${tgt} PRIVATE xpro::node xpro::gtest_main)
set_target_properties(${tgt} PROPERTIES OUTPUT_NAME "${tgt}" PREFIX "" SUFFIX ".node")
if(APPLE)
  target_link_options(${tgt} PUBLIC -undefined dynamic_lookup)
endif()
set(testJs $<TARGET_FILE_DIR:${tgt}>/${tgt}.js)
file(READ ${pro}.js ${pro}_js)
file(CONFIGURE OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${pro}.js CONTENT "${${pro}_js}" @ONLY)
file(GENERATE OUTPUT ${testJs} INPUT ${CMAKE_CURRENT_BINARY_DIR}/${pro}.js)
xpGetPkgVar(nodexp EXE)
add_test(NAME ${tgt} COMMAND ${nodexp_EXE} ${testJs} WORKING_DIRECTORY $<TARGET_FILE_DIR:${tgt}>)
