set(pro protobuf)
set(tgt ${pro}_test)
set(proto_srcs person.proto schema.proto)
add_executable(${tgt} person.cpp ${pro}.cpp)
PROTOBUF_GENERATE_CPP(PROTO_SRCS PROTO_HDRS ${proto_srcs})
target_sources(${tgt} PRIVATE ${PROTO_SRCS} ${PROTO_HDRS})
target_include_directories(${tgt} PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(${tgt} PRIVATE ${${pro}_deps})
add_test(NAME ${tgt} COMMAND ${tgt})
