set(pro flatbuffers)
set(tgt ${pro}_test)
set(fbs_srcs schema.fbs)
add_executable(${tgt} ${pro}.cpp)
set(xpfb ${flatbuffers_DIR}/../cmake/xpflatbuffers.cmake)
if(NOT COMMAND xpFlatBuffersBuild AND EXISTS ${xpfb})
  include(${xpfb})
endif()
if(TARGET flatbuffers)
  set(fb flatbuffers)
elseif(TARGET flatbuffers::flatbuffers)
  set(fb flatbuffers::flatbuffers)
endif()
xpFlatBuffersBuild(TARGET ${tgt} SCHEMAS ${fbs_srcs})
target_link_libraries(${tgt} PRIVATE ${fb} xpro::gtest_main)
target_compile_features(${tgt} PRIVATE ${${pro}_compile_features})
add_test(NAME ${tgt} COMMAND ${tgt})
