set(pro flatbuffers)
set(tgt ${pro}_test)
set(fbs_srcs schema.fbs)
add_executable(${tgt} ${pro}.cpp)
xpFlatBuffersBuild(TARGET ${tgt} SCHEMAS ${fbs_srcs})
target_link_libraries(${tgt} PRIVATE xpro::flatbuffers xpro::gtest_main)
target_compile_features(${tgt} PRIVATE ${${pro}_compile_features})
add_test(NAME ${tgt} COMMAND ${tgt})
