# CRTool
ARG CRTOOL
RUN eval "${CRTOOL}"
ENV PATH=$PATH:${EXTERN_DIR}/CRTool
# PluginSDK
ARG PLUGINSDK
RUN eval "${PLUGINSDK}"
# internpro
ARG INTERNPRO
RUN eval "${INTERNPRO}"
ARG INTERNPRO_PATH="${EXTERN_DIR}/internpro*"
ENV INTERNPRO_PATH=${INTERNPRO_PATH}
# webpro
ARG WEBPRO
RUN eval "${WEBPRO}"
ARG WEBPRO_PATH="${EXTERN_DIR}/webpro*"
ENV WEBPRO_PATH=${WEBPRO_PATH}
