name: rocky-pin
on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pin.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pin.dockerfile'
  workflow_dispatch:
  workflow_run:
    workflows: ["rocky-pro"]
    types:
      - completed
jobs:
  rocky-pin:
    if: |
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/buildpro.yml
    with:
      img: rocky-pin
      platforms: "linux/amd64,linux/arm64"
