name: rocky-pdv
on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pdv.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pdv.dockerfile'
  workflow_dispatch:
  workflow_run:
    workflows: ["rocky8-gcc9"]
    types:
      - completed
jobs:
  rocky-pdv:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write
    if: |
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/buildpro.yml
    with:
      img: rocky-pdv
