name: Build rocky-pro image

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pro.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pro.dockerfile'
  workflow_dispatch:

jobs:
  rocky:
    uses: externpro/actpro/.github/workflows/buildpro.yml@main
    with:
      img: rocky-pro
