name: Build rocky-pdv image

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pdv.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pdv.dockerfile'
  workflow_dispatch:
  workflow_run:
    workflows: ["rocky-pro"]
    types:
      - completed

jobs:
  rocky-pdv:
    uses: externpro/actpro/.github/workflows/buildpro.yml@main
    with:
      img: rocky-pdv
