name: rocky10-gcc15
on:
  push:
    branches: ["xpro"]
    paths:
      - 'public/rocky10-gcc15.dockerfile'
  pull_request:
    branches: ["xpro"]
    paths:
      - 'public/rocky10-gcc15.dockerfile'
  workflow_dispatch:
jobs:
  rocky10-gcc15:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write
      artifact-metadata: write
    uses: ./.github/workflows/buildpro.yml
    with:
      img: rocky10-gcc15
      platforms: "linux/amd64,linux/arm64"
