name: Build rocky-ci image

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-ci.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-ci.dockerfile'
  workflow_dispatch:

jobs:
  rocky-ci:
    uses: externpro/actpro/.github/workflows/buildpro.yml@main
    with:
      img: rocky-ci
