name: rocky-pro

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pro.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/rocky-pro.dockerfile'
  workflow_dispatch:

jobs:
  rocky-pro:
    uses: externpro/actpro/.github/workflows/buildpro.yml@main
    with:
      img: rocky-pro
      platforms: "linux/amd64,linux/arm64"
