name: ubuntu
on:
  push:
    branches: [ "dev" ]
    paths:
      - 'public/ubuntu.dockerfile'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'public/ubuntu.dockerfile'
  workflow_dispatch:
jobs:
  ubuntu:
    uses: ./.github/workflows/buildpro.yml
    with:
      img: ubuntu
      platforms: "linux/amd64,linux/arm64"
