name: ubuntu
on:
  push:
    branches: ["xpro"]
    paths:
      - 'public/ubuntu.dockerfile'
  pull_request:
    branches: ["xpro"]
    paths:
      - 'public/ubuntu.dockerfile'
  workflow_dispatch:
jobs:
  ubuntu:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write
    uses: ./.github/workflows/buildpro.yml
    with:
      img: ubuntu
      platforms: "linux/amd64,linux/arm64"
